# Generated by Django 4.1.3 on 2022-11-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetbalspelers',
        ),
    ]
